"use client";
import {useState} from "react";

type Fact={field:string;value:string|null;quote:string|null;status:string};
type Flag={severity:string;code:string;message:string;section:string};
type Result={run_id:string;status:string;facts:Fact[];retrieved_examples:string[];proposal_markdown:string;flags:Flag[];provider:string};
const transcript=`Maya: We're Northstar Studio, a 75-person product design and development agency.\nMaya: The problem is proposals take two or three days after a good discovery call.\nOmar: We want to get a strong first draft in front of the account owner within 30 minutes. A human must review it.\nMaya: We need this in the next 6 weeks.\nOmar: We have not approved a budget yet. Do not guess one.`;
const past=`Delivery approach\nWe begin with discovery and workflow mapping, then deliver in short checkpoints, followed by acceptance testing and handover.\n\nSafety\nGenerated content is always a draft. Unsupported claims are flagged and a named human approves the final output.`;
export default function Home(){const[t,setT]=useState(transcript);const[p,setP]=useState(past);const[r,setR]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[approved,setApproved]=useState(false);async function run(){setBusy(true);setApproved(false);try{const res=await fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/v1/proposals`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transcript:t,past_proposals:[p]})});if(!res.ok)throw new Error(await res.text());setR(await res.json())}catch(e){alert(`Could not generate: ${e instanceof Error?e.message:"unknown error"}`)}finally{setBusy(false)}}function download(){if(!r||!approved)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([r.proposal_markdown],{type:"text/markdown"}));a.download=`proposal-${r.run_id}.md`;a.click()}
return <main className="shell"><div className="hero"><div><div className="eyebrow">Human-reviewed sales workflow</div><h1>From call to proposal, without invented promises.</h1><div className="lede">Extract facts with evidence, reuse the best parts of past proposals, flag risky claims, then hold the draft for approval.</div></div><div className="badge">Nothing sends automatically</div></div><div className="grid"><section className="card"><div className="step">01 · INPUT</div><h2>Discovery call transcript</h2><div className="small">Fictional sample. Paste exported Zoom, Meet or Teams text.</div><textarea value={t} onChange={e=>setT(e.target.value)}/><label>Past proposal library</label><textarea value={p} onChange={e=>setP(e.target.value)}/><button className="primary" onClick={run} disabled={busy}>{busy?"Building evidence-backed draft…":"Build proposal draft"}</button></section><section className="card"><div className="step">02 · EVIDENCE</div><h2>Deal facts and source quotes</h2>{!r?<div className="empty">Run the workflow to see what was supported, what stayed unknown and what needs review.</div>:<>{r.facts.map(f=><div className="fact" key={f.field}><strong>{f.field}</strong><div><div>{f.value||"Unknown"} · {f.status}</div>{f.quote&&<div className="quote">“{f.quote}”</div>}</div></div>)}<label>Verifier findings</label>{r.flags.map(f=><div className={`flag ${f.severity}`} key={f.code}><strong>{f.severity.toUpperCase()}</strong> · {f.message}</div>)}</>}</section>{r&&<><section className="card span"><div className="step">03 · REVIEW GATE</div><h2>Proposal draft</h2><div className="proposal">{r.proposal_markdown}</div><div className="actions"><button className="secondary" onClick={()=>setApproved(false)}>Needs changes</button><button className="primary" style={{width:"auto",margin:0}} onClick={()=>setApproved(true)}>Approve draft</button><button className="secondary" disabled={!approved} onClick={download}>Export .md</button></div><p className="small">Run {r.run_id} · {r.provider} · {approved?"Approved for export":"Export locked until approval"}</p></section></>}</div></main>}
